"""Context generator -- produces AGENTS.md and harness config from a CodebaseProfile."""

from __future__ import annotations

from devharness.onboarding.scanner import CodebaseProfile


def generate_agents_md(profile: CodebaseProfile) -> str:
    """Generate an AGENTS.md file tailored to the detected codebase."""
    sections: list[str] = []

    # Header
    sections.append("# AGENTS.md")
    sections.append("")
    sections.append("This file was auto-generated by `harness init`. Edit it to refine agent behavior.")
    sections.append("")

    # Project overview
    sections.append("## Project Overview")
    sections.append("")
    type_labels = []
    if profile.web_app:
        type_labels.append("web application")
    if profile.api_app:
        type_labels.append("API service")
    if profile.cli_app:
        type_labels.append("CLI tool")
    if profile.library:
        type_labels.append("library/package")
    if not type_labels:
        type_labels.append("software project")

    sections.append(f"- **Type:** {', '.join(type_labels)}")
    sections.append(f"- **Primary language:** {profile.primary_language}")
    if profile.frameworks:
        sections.append(f"- **Frameworks:** {', '.join(profile.frameworks)}")
    if profile.package_managers:
        sections.append(f"- **Package managers:** {', '.join(profile.package_managers)}")
    sections.append(f"- **Estimated size:** {profile.estimated_size}")
    sections.append("")

    # Directory structure
    if profile.directory_structure:
        sections.append("## Directory Structure")
        sections.append("")
        sections.append("```")
        for dirname, files in sorted(profile.directory_structure.items()):
            sections.append(f"{dirname}/")
            for f in files[:5]:
                sections.append(f"  {f}")
            if len(files) > 5:
                sections.append(f"  ... ({len(files) - 5} more)")
        sections.append("```")
        sections.append("")

    # Commands
    sections.append("## Commands")
    sections.append("")
    commands = [
        ("Test", profile.test_command),
        ("Lint", profile.lint_command),
        ("Format", profile.format_command),
        ("Build", profile.build_command),
        ("Type check", profile.type_check_command),
        ("Dev server", profile.dev_server_command),
    ]
    for label, cmd in commands:
        if cmd:
            sections.append(f"- **{label}:** `{cmd}`")
    if not any(cmd for _, cmd in commands):
        sections.append("_No commands detected. Add them manually._")
    sections.append("")

    # Entry points
    if profile.entry_points:
        sections.append("## Entry Points")
        sections.append("")
        for ep in profile.entry_points:
            sections.append(f"- `{ep}`")
        sections.append("")

    # Conventions
    sections.append("## Conventions")
    sections.append("")
    sections.extend(_generate_conventions(profile))
    sections.append("")

    # Framework-specific instructions
    fw_instructions = _generate_framework_instructions(profile)
    if fw_instructions:
        sections.append("## Framework Notes")
        sections.append("")
        sections.extend(fw_instructions)
        sections.append("")

    # CI/CD
    if profile.has_ci:
        sections.append("## CI/CD")
        sections.append("")
        sections.append(f"- CI system: {profile.ci_system}")
        sections.append("- Ensure all changes pass CI before considering work complete.")
        sections.append("")

    # Agent rules
    sections.append("## Agent Rules")
    sections.append("")
    sections.append("1. Read existing code before modifying it.")
    sections.append("2. Run tests after every change.")
    sections.append("3. Follow the existing code style and conventions.")
    sections.append("4. Do not modify files outside the workspace root.")
    sections.append("5. When uncertain, ask rather than guess.")
    if profile.lint_command:
        sections.append(f"6. Run `{profile.lint_command}` before finishing work.")
    if profile.format_command:
        sections.append(
            f"{'7' if profile.lint_command else '6'}. Run `{profile.format_command}` "
            "to format code before committing."
        )
    sections.append("")

    return "\n".join(sections)


def generate_harness_config(profile: CodebaseProfile) -> dict:
    """Generate harness configuration dict from the profile.

    Returns a dict suitable for storing in the harness DB as project settings.
    """
    config: dict = {
        "profile": {
            "primary_language": profile.primary_language,
            "languages": profile.languages,
            "frameworks": profile.frameworks,
            "package_managers": profile.package_managers,
            "estimated_size": profile.estimated_size,
            "web_app": profile.web_app,
            "api_app": profile.api_app,
            "cli_app": profile.cli_app,
            "library": profile.library,
        },
        "commands": {
            "test": profile.test_command,
            "lint": profile.lint_command,
            "format": profile.format_command,
            "build": profile.build_command,
            "type_check": profile.type_check_command,
            "dev_server": profile.dev_server_command,
        },
        "observers": _build_observer_config(profile),
        "hooks": _build_hook_config(profile),
        "skills": _build_skills_config(profile),
        "browser_test_flows": _build_browser_flows(profile),
    }
    return config


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _generate_conventions(profile: CodebaseProfile) -> list[str]:
    lines: list[str] = []
    lang = profile.primary_language

    if lang == "python":
        lines.append("- Follow PEP 8 style guidelines.")
        lines.append("- Use type hints for function signatures.")
        if "pydantic" in profile.frameworks:
            lines.append("- Use Pydantic models for data validation.")
        if "ruff" in (profile.lint_command or ""):
            lines.append("- Ruff is used for linting and formatting. Follow its rules.")
        if "pytest" in profile.test_frameworks:
            lines.append("- Tests use pytest. Place tests in the `tests/` directory.")
    elif lang in ("typescript", "javascript"):
        lines.append("- Use consistent import style (check existing code).")
        if "eslint" in (profile.lint_command or "") or any(
            "eslint" in f for f in profile.config_files
        ):
            lines.append("- ESLint is configured. Follow its rules.")
        if any("prettier" in f for f in profile.config_files):
            lines.append("- Prettier is used for formatting.")
        if "typescript" in profile.languages:
            lines.append("- Use TypeScript types; avoid `any`.")
    elif lang == "go":
        lines.append("- Follow standard Go conventions (gofmt, go vet).")
        lines.append("- Use table-driven tests.")
        lines.append("- Handle errors explicitly; do not ignore them.")
    elif lang == "rust":
        lines.append("- Follow Rust conventions (cargo fmt, clippy).")
        lines.append("- Prefer returning `Result` over panicking.")

    if not lines:
        lines.append("- Follow the existing code style found in the repository.")

    return lines


def _generate_framework_instructions(profile: CodebaseProfile) -> list[str]:
    lines: list[str] = []

    if "django" in profile.frameworks:
        lines.append("- Django project. Use the ORM for database operations.")
        lines.append("- Create/update migrations when modifying models (`python manage.py makemigrations`).")
        lines.append("- Follow Django's app-based architecture.")
    if "fastapi" in profile.frameworks:
        lines.append("- FastAPI project. Use async endpoints where possible.")
        lines.append("- Use Pydantic models for request/response schemas.")
        lines.append("- Use dependency injection for shared resources.")
    if "flask" in profile.frameworks:
        lines.append("- Flask project. Use blueprints for organizing routes.")
    if "react" in profile.frameworks:
        lines.append("- React project. Prefer functional components with hooks.")
        lines.append("- Keep components small and focused.")
    if "next" in profile.frameworks:
        lines.append("- Next.js project. Use the App Router pattern if `app/` directory exists.")
        lines.append("- Use Server Components by default; add 'use client' only when needed.")
    if "vue" in profile.frameworks:
        lines.append("- Vue project. Use Composition API with `<script setup>`.")
    if "express" in profile.frameworks:
        lines.append("- Express project. Use middleware for cross-cutting concerns.")
        lines.append("- Use error-handling middleware for consistent error responses.")
    if "sqlalchemy" in profile.frameworks:
        lines.append("- SQLAlchemy is used for database access. Use the session pattern.")

    return lines


def _build_observer_config(profile: CodebaseProfile) -> dict:
    """Configure observers based on detected tech stack."""
    observers: dict = {}

    # Process observer -- always useful
    observers["process"] = {"enabled": True}

    # Test watcher -- if we have tests
    if profile.test_command:
        observers["test_watcher"] = {
            "enabled": True,
            "command": profile.test_command,
        }

    # Log watcher -- if it's a server app
    if profile.api_app or profile.web_app:
        observers["log_watcher"] = {
            "enabled": True,
            "patterns": ["*.log", "logs/*.log"],
        }

    # Endpoint health -- if it's a web/API app
    if profile.dev_server_command:
        port = "3000" if profile.primary_language in ("typescript", "javascript") else "8000"
        observers["endpoint_health"] = {
            "enabled": True,
            "endpoints": [f"http://localhost:{port}/"],
        }

    return observers


def _build_hook_config(profile: CodebaseProfile) -> dict:
    """Configure hooks based on detected tooling."""
    hooks: dict = {}

    if profile.format_command:
        hooks["format"] = {
            "event": "post_turn",
            "command": profile.format_command,
        }

    if profile.type_check_command:
        hooks["type_check"] = {
            "event": "post_turn",
            "command": profile.type_check_command,
        }

    if profile.lint_command:
        hooks["lint"] = {
            "event": "post_turn",
            "command": profile.lint_command,
        }

    if profile.test_command:
        hooks["test"] = {
            "event": "post_turn",
            "command": profile.test_command,
        }

    return hooks


def _build_skills_config(profile: CodebaseProfile) -> list[str]:
    """Select default skills based on project type."""
    skills = ["coding_general"]

    if profile.test_command:
        skills.append("test_fixer")

    return skills


def _build_browser_flows(profile: CodebaseProfile) -> list[dict]:
    """Generate browser test flow stubs for web apps."""
    if not profile.web_app:
        return []

    port = "3000" if profile.primary_language in ("typescript", "javascript") else "8000"
    base_url = f"http://localhost:{port}"

    flows = [
        {
            "name": "homepage_loads",
            "url": base_url,
            "steps": [
                {"action": "wait_for", "selector": "body", "timeout": 10000},
            ],
            "assertions": [
                {"type": "element_visible", "selector": "body"},
                {"type": "no_console_errors"},
            ],
        },
    ]

    return flows
