"""Hook generator -- produces shell scripts in .devharness/hooks/ for detected tooling."""

from __future__ import annotations

from pathlib import Path

from devharness.onboarding.scanner import CodebaseProfile


_HOOK_HEADER = """#!/usr/bin/env bash
# Auto-generated by harness init. Edit as needed.
set -euo pipefail
"""


def generate_hooks(profile: CodebaseProfile, hooks_dir: Path | None = None) -> dict[str, str]:
    """Generate hook shell scripts.

    If *hooks_dir* is provided the scripts are written to disk and made
    executable.  Either way a ``{name: script_content}`` dict is returned so
    callers can persist hooks however they prefer.
    """
    hooks: dict[str, str] = {}

    if profile.format_command:
        hooks["format"] = _build_script(profile.format_command, "Format code")

    if profile.type_check_command:
        hooks["typecheck"] = _build_script(profile.type_check_command, "Type check")

    if profile.test_command:
        hooks["test"] = _build_script(profile.test_command, "Run tests")

    if profile.lint_command:
        hooks["lint"] = _build_script(profile.lint_command, "Lint code")

    if profile.build_command:
        hooks["build"] = _build_script(profile.build_command, "Build project")

    if hooks_dir is not None:
        hooks_dir.mkdir(parents=True, exist_ok=True)
        for name, content in hooks.items():
            path = hooks_dir / f"{name}.sh"
            path.write_text(content)
            path.chmod(0o755)

    return hooks


def _build_script(command: str, description: str) -> str:
    """Build the shell script content for a hook."""
    return f"""{_HOOK_HEADER}
# {description}
echo "[harness] Running: {command}"
{command}
"""
